export const dialogCont = {
    header: {
        avatar: "https://pp.userapi.com/c837329/v837329238/59b87/MWRxBE4dXJk.jpg",
        title: "Андрей (Sberbank)"
    },
    content: [
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        },
        {
            position: 'right',
            type: 'text',
            text: 'лох',
            date: new Date(),
        },
        {
            position: 'left',
            type: 'text',
            text: 'Привет',
            date: new Date(),
        }

    ]
}
